# Generated by Django 4.0.5 on 2022-06-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_created_date_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='updated_at',
        ),
    ]
