# Generated by Django 4.0.5 on 2022-06-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_task_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to=None,
        ),
    ]
